version: '3'

services:
  zookeeper:
    image: zookeeper:3.5
    container_name: zookeeper
    hostname: zookeeper

  clickhouse-node1:
    image: yandex/clickhouse-server:21.3.20.1
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    ports:
      - "9091:9000"
    volumes:
      - ./clickhouse_config/node1:/etc/clickhouse-server
    depends_on:
      - zookeeper

  clickhouse-node2:
    image: yandex/clickhouse-server:21.3.20.1
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    volumes:
      - ./clickhouse_config/node2:/etc/clickhouse-server
    depends_on:
      - zookeeper

  clickhouse-node3:
    image: yandex/clickhouse-server:21.3.20.1
    container_name: clickhouse-node3
    hostname: clickhouse-node3
    ports:
      - "9093:9000"
    volumes:
      - ./clickhouse_config/node3:/etc/clickhouse-server
    depends_on:
      - zookeeper

  clickhouse-node4:
    image: yandex/clickhouse-server:21.3.20.1
    container_name: clickhouse-node4
    hostname: clickhouse-node4
    volumes:
      - ./clickhouse_config/node4:/etc/clickhouse-server
    depends_on:
      - zookeeper
